# Generated by Django 2.2.2 on 2019-07-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_group', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('value', models.FloatField(default=0.0)),
                ('ticket', models.IntegerField(default=1)),
            ],
        ),
    ]
