# Generated by Django 5.2.6 on 2025-10-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
