import { vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { EventStation } from './EventStation';
import { eventApi, DinnerEvent, FoodItem } from './eventApi';
vi.mock('../../contexts/AuthContext',()=>({useAuth:()=>({user:{id:1}})}));
vi.mock('./eventApi', async()=>({...await vi.importActual('./eventApi'),eventApi:{checkout:vi.fn()}}));
const event: DinnerEvent={id:1,name:'Dinner',event_date:'2026-09-17',closed:false,collect_tickets:true};
const foods: FoodItem[]=[{id:1,name:'Pasta',food_group:'Dinner',value:0,ticket:3,is_available:true,created_at:''}];
beforeEach(()=>{ vi.mocked(eventApi.checkout).mockReset(); });
it('requires ticket confirmation and keeps the same request after a lost response',async()=>{
  vi.mocked(eventApi.checkout).mockRejectedValueOnce(new Error('network'));
  render(<EventStation event={event} foods={foods} connected />);
  fireEvent.click(screen.getByRole('button',{name:'Add Pasta'}));
  fireEvent.click(screen.getByRole('button',{name:/Check order ·/}));
  expect(screen.getByRole('button',{name:'Send to kitchen'})).toBeDisabled();
  fireEvent.click(screen.getByLabelText('I collected 3 tickets'));
  fireEvent.click(screen.getByRole('button',{name:'Send to kitchen'}));
  await screen.findByRole('button',{name:'Retry same order'});
  const first=vi.mocked(eventApi.checkout).mock.calls[0][1];
  expect(first.tickets_collected).toBe(3);
  expect(first.items).toEqual([{food_item_id:1,quantity:1}]);
  expect(screen.getByRole('button',{name:'1. Menu'})).toBeDisabled();
  vi.mocked(eventApi.checkout).mockResolvedValueOnce({id:4,display_id:1001,customer_name:'Walk-up',order_items:[{quantity:1,unit_tickets:3}]} as any);
  fireEvent.click(screen.getByRole('button',{name:'Retry same order'}));
  await screen.findByText('#1001');
  expect(vi.mocked(eventApi.checkout).mock.calls[1][1]).toEqual(first);
  expect(JSON.parse(localStorage.getItem('event-draft:1:1')!).pending).toBeNull();
});
it('restores an interrupted request after reload without collecting tickets twice',async()=>{
  const pending={customer_name:'Table 2',checkout_key:'same-request',tickets_collected:6,items:[{food_item_id:1,quantity:2}]};
  localStorage.setItem('event-draft:1:1',JSON.stringify({quantities:{1:2},name:'Table 2',pending}));
  vi.mocked(eventApi.checkout).mockImplementation(()=>new Promise(()=>{}));
  render(<EventStation event={event} foods={foods} connected />);
  fireEvent.click(screen.getByRole('button',{name:'Retry same order'}));
  await waitFor(()=>expect(eventApi.checkout).toHaveBeenCalledWith(1,pending));
});
it('blocks checkout when disconnected and hides order entry for closed events',()=>{
  const {rerender}=render(<EventStation event={event} foods={foods} connected={false} />);
  fireEvent.click(screen.getByRole('button',{name:'Add Pasta'}));
  fireEvent.click(screen.getByRole('button',{name:/Check order ·/}));
  fireEvent.click(screen.getByLabelText('I collected 3 tickets'));
  expect(screen.getByRole('button',{name:'Send to kitchen'})).toBeDisabled();
  rerender(<EventStation event={{...event,closed:true}} foods={foods} connected />);
  expect(screen.getByText('This event is closed')).toBeInTheDocument();
});
it('sends a guest order without claiming tickets were collected and preserves the handoff number',async()=>{
  vi.mocked(eventApi.checkout).mockResolvedValueOnce({id:8,display_id:1008,customer_name:'Walk-up',awaiting_tickets:true,order_items:[{quantity:1,unit_tickets:3}]} as any);
  const {unmount}=render(<EventStation event={event} foods={foods} connected guest />);
  fireEvent.click(screen.getByRole('button',{name:'Add Pasta'}));
  expect(screen.queryByRole('checkbox')).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button',{name:/Check order ·/}));
  expect(eventApi.checkout).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button',{name:'Send to ticket desk'}));
  await screen.findByText('Bring this number to the ticket desk');
  expect(vi.mocked(eventApi.checkout).mock.calls[0][1].tickets_collected).toBe(0);
  await waitFor(()=>expect(JSON.parse(localStorage.getItem('event-draft:1:1')!).receipt.display_id).toBe(1008));
  unmount();
  render(<EventStation event={event} foods={foods} connected guest />);
  expect(screen.getByText('#1008')).toBeInTheDocument();
});
it('keeps drafts and checkout room routing separate between rooms',async()=>{
  vi.mocked(eventApi.checkout).mockRejectedValueOnce(new Error('network'));
  const {rerender}=render(<EventStation key="wings" event={event} foods={foods} connected roomId={10} roomName="Wings" />);
  fireEvent.click(screen.getByRole('button',{name:'Add Pasta'}));
  rerender(<EventStation key="sandwich" event={event} foods={foods} connected roomId={11} roomName="Sandwiches" />);
  expect(screen.getByText('Tap a menu item to begin.')).toBeInTheDocument();
  rerender(<EventStation key="wings" event={event} foods={foods} connected roomId={10} roomName="Wings" />);
  expect(screen.getByLabelText('Pasta quantity')).toHaveTextContent('1');
  fireEvent.click(screen.getByRole('button',{name:/Check order ·/}));
  fireEvent.click(screen.getByLabelText('I collected 3 tickets'));
  fireEvent.click(screen.getByRole('button',{name:'Send to kitchen'}));
  await screen.findByRole('button',{name:'Retry same order'});
  expect(vi.mocked(eventApi.checkout).mock.calls[0][1].room_id).toBe(10);
  expect(JSON.parse(localStorage.getItem('event-draft:1:1:room:10')!).pending.room_id).toBe(10);
  expect(JSON.parse(localStorage.getItem('event-draft:1:1:room:11')!).pending).toBeNull();
});
it('collects one total and recovers a mixed-kitchen check after a lost response',async()=>{
  const checkout=vi.fn().mockRejectedValueOnce(new Error('network'));
  eventApi.stationCheckout=checkout;
  const rooms=[{id:1,event_id:1,name:'Fried',food_item_ids:[1]},{id:2,event_id:1,name:'Grilled',food_item_ids:[2]}];
  const menu=[...foods,{...foods[0],id:2,name:'Burger',ticket:4}];
  const {unmount}=render(<EventStation event={event} foods={menu} rooms={rooms} stationNumber={6} connected />);
  fireEvent.click(screen.getByRole('button',{name:'Add Pasta'}));
  fireEvent.click(screen.getByRole('button',{name:'Add Burger'}));
  fireEvent.click(screen.getByRole('button',{name:'Check order · 7 tickets'}));
  expect(screen.getByRole('button',{name:'Send to kitchen'})).toBeDisabled();
  fireEvent.click(screen.getByLabelText('I collected 7 tickets'));
  fireEvent.click(screen.getByRole('button',{name:'Send to kitchen'}));
  await screen.findByRole('button',{name:'Retry same order'});
  const first=checkout.mock.calls[0][1];
  expect(first.station_number).toBe(6);
  expect(first.tickets_collected).toBe(7);
  expect(first.items).toHaveLength(2);
  unmount();
  checkout.mockResolvedValueOnce({id:12,station_number:6,orders:[{id:9,display_id:9,room_id:1,customer_name:'Walk-up',order_items:[{quantity:1,unit_tickets:3}]},{id:10,display_id:10,room_id:2,customer_name:'Walk-up',order_items:[{quantity:1,unit_tickets:4}]}]});
  render(<EventStation event={event} foods={menu} rooms={rooms} stationNumber={6} connected />);
  fireEvent.click(screen.getByRole('button',{name:'Retry same order'}));
  await screen.findByText('Check #12');
  expect(checkout.mock.calls[1][1]).toEqual(first);
  expect(screen.getByText('Walk-up · 7 tickets collected')).toBeInTheDocument();
});
