# Generated by Django 2.2.2 on 2019-07-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20190711_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ManyToManyField(to='shopping_cart.Item'),
        ),
    ]
