# Generated by Django 2.2.2 on 2019-07-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_transaction_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
        migrations.AddField(
            model_name='transaction',
            name='inventory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.Item'),
            preserve_default=False,
        ),
    ]
