# Generated by Django 2.2.2 on 2019-07-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_auto_20190716_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='inventory',
        ),
        migrations.AddField(
            model_name='transaction',
            name='inventory',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.Inventory'),
            preserve_default=False,
        ),
    ]
