# Generated by Django 2.2.2 on 2019-07-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_front', '0001_initial'),
        ('shopping_cart', '0016_auto_20190716_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='inventory',
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ManyToManyField(to='shop_front.FoodItem'),
        ),
    ]
