# Generated by Django 5.2.6 on 2025-09-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0017_auto_20190717_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='invetory',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
