# Generated by Django 5.2.7 on 2025-10-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0021_alter_transaction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_preparing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_ready',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_status_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
