# Generated by Django 5.2.7 on 2025-10-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0022_transaction_date_complete_transaction_date_preparing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
